target "PLTransitionExample" do
pod 'Masonry'
pod 'PLTransition', :path => '../PLTransition.podspec'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['CLANG_ENABLE_MODULES'] = 'NO'
            # 在生成的 Pods 项目文件中加入 CC 参数，路径的值根据你自己的项目来修改
            config.build_settings['CC'] = '$(SRCROOT)/../../ccache-clang'
        end
    end
end
